import numpy as np

# For contact
MIN_VOLUME = 0.0
# for BBOX
SCALE_FACTOR = 1.1
MIN_SCALE_DELTA = 0.01
MAX_SCALE_DELTA = 0.075

# for ICP
PC_SIZE = 2048
HAUS_DIST_TRHESHOLD = 0.125
ICP_FITNESS_THRESHOLD = 0.80
ICP_THRESHOLD = 0.05
MAX_ICP_ITER = 2000

# For rotation candidates
ROT_HAUS_DIST_THRESHOLD = HAUS_DIST_TRHESHOLD * 2
NOISE_AMT = 0.001
COSINE_THRESHOLD = 0.95# 0.90
AXIS_COSINE_THRESHOLD = 0.98
CROSS_THRESHOLD = 0.075# 0.1 
# For relation pruning
ROT_AMOUNT_THRESHOLD = np.pi/24
ROT_MIN = (-ROT_AMOUNT_THRESHOLD % (2*np.pi))
ROT_MAX = (ROT_AMOUNT_THRESHOLD % (2*np.pi))

TRANS_AMOUNT_THRESHOLD = 0.05
REF_TRANS_AMOUNT_THRESHOLD = 0.1
TRANSLATION_ROTATION_THRESHOLD = np.pi * 0.1
REF_AXIS_ALIGNMENT_THRESHOLD = 0.99
TR_R_MIN = (-TRANSLATION_ROTATION_THRESHOLD % (2*np.pi))
TR_R_MAX = (TRANSLATION_ROTATION_THRESHOLD % (2*np.pi))


MIN_SIZE_RELATION_GROUP = 2# 3
DIV_THRESHOLD = 0.075
REF_DIV_THRESHOLD = 0.06
INTER_TO_POINT_RATIO_FACTOR = 0.75